export const projects = [
  {
    title: "plantit",
    type: "desarrollo web",
    thumb: "3.png",
    path: "assets/portfolio/plantit",
    portada: "portada.jpg",
    pathUrl: "plantit",
    thumbCarrusel: "assets/portfolio/carruselHome/plantit.png",
    fotos: [
      {
        src: "1.png",
        isFullScreen: true,
        noParallax: true,
      },
      {
        src: "4.png",
        isFullScreen: false,
        noParallax: false,
      },
      {
        src: "2.png",
        isFullScreen: false,
        noParallax: false,
      },
      {
        src: "5.png",
        isFullScreen: true,
        noParallax: false,
      },
      {
        src: "3.png",
        isFullScreen: true,
        noParallax: true,
      },
    ],
    id: 1,
  },
  {
    title: "Ensamble Gráfico",
    type: "diseño y desarrollo web",
    thumb: "ensamble.png",
    path: "assets/portfolio/ensamble",
    url: "http://ensamblegrafico.com.ar/",
    portada: "portada.png",
    pathUrl: "ensamble",
    thumbCarrusel: "assets/portfolio/carruselHome/ensamble.png",

    fotos: [
      {
        src: "1.png",
        isFullScreen: false,
        noParallax: true,
      },
      {
        src: "portada.png",
        isFullScreen: true,
        noParallax: false,
      },
      {
        src: "ensamble.png",
        isFullScreen: true,
        noParallax: true,
        noPadding: false,
      },
    ],
    id: 2,
  },
  {
    title: "xborderpack",
    type: "desarrollo web",
    thumb: "xborderpack.png",
    path: "assets/portfolio/xborderpack",
    url: "http://www.xborderpack.com/",
    portada: "portada.png",
    pathUrl: "xborder",
    thumbCarrusel: "assets/portfolio/carruselHome/xborderpack.png",
    fotos: [
      {
        src: "3.png",
        isFullScreen: true,
        noParallax: true,
      },
      {
        src: "xborderpack.png",
        isFullScreen: true,
        noParallax: true,
      },
      {
        src: "2.gif",
        isFullScreen: true,
        noParallax: true,
      },
      {
        src: "portada.png",
        isFullScreen: true,
        noParallax: true,
      },
    ],
    id: 3,
  },
  {
    title: "crowdvac",
    type: "desarrollo web",
    thumb: "crowdvac.png",
    path: "assets/portfolio/crowdvac",
    portada: "portada.png",
    pathUrl: "crowdvac",
    thumbCarrusel: "assets/portfolio/carruselHome/crowdvac.png",
    fotos: [
      {
        src: "1.png",
        isFullScreen: true,
        noParallax: true,
      },
      {
        src: "crowdvac.gif",
        isFullScreen: true,
        noParallax: true,
      },
      {
        src: "2.png",
        isFullScreen: true,
        noParallax: true,
      },
      {
        src: "portada.png",
        isFullScreen: true,
        noParallax: true,
      },
    ],
    id: 5,
  },
  {
    title: "Cipriani",
    type: "desarrollo web",
    thumb: "cipriani.png",
    path: "assets/portfolio/cipriani",
    portada: "portada.png",
    url: "http://www.soleorona.com/cipriani/",
    pathUrl: "cipriani",
    thumbCarrusel: "assets/portfolio/carruselHome/cipriani.png",
    fotos: [
      {
        src: "1.png",
        isFullScreen: true,
        noParallax: true,
      },
      {
        src: "cipriani.gif",
        isFullScreen: true,
        noParallax: true,
      },
      {
        src: "portada.png",
        isFullScreen: true,
        noParallax: true,
      },
    ],
    id: 6,
  },
  {
    title: "Ariela",
    type: "desarrollo y diseño web",
    thumb: "ariela_old.png",
    path: "assets/portfolio/ariela_old",
    portada: "portada.png",
    url: "http://arielapaula.com/old_web",
    pathUrl: "ariela",
    thumbCarrusel: "assets/portfolio/carruselHome/ariela.png",
    paragraph:
      "Diseño y desarrollo anterior de mi página, decidí actualizarla para poder implementar nuevas tecnologías y poder actualizar el diseño también",
    fotos: [
      {
        src: "1.jpg",
        isFullScreen: true,
        noParallax: true,
        noPadding: true,
      },
      {
        src: "2.gif",
        isFullScreen: true,
        noParallax: true,
        noPadding: true,
      },
      {
        src: "3.jpg",
        isFullScreen: true,
        noParallax: true,
        noPadding: true,
      },
      {
        src: "4.gif",
        isFullScreen: true,
        noParallax: true,
        noPadding: true,
      },
      {
        src: "5.jpg",
        isFullScreen: true,
        noParallax: true,
        noPadding: true,
      },
      {
        src: "6.gif",
        isFullScreen: true,
        noParallax: true,
        noPadding: true,
      },
      {
        src: "7.jpg",
        isFullScreen: true,
        noParallax: true,
        noPadding: true,
      },
      {
        src: "8.gif",
        isFullScreen: true,
        noParallax: true,
        noPadding: true,
      },
      {
        src: "9.jpg",
        isFullScreen: true,
        noParallax: true,
        noPadding: true,
      },
    ],
    id: 7,
  },
];
